ui <- dashboardPage(
  dashboardHeader(title = "Majestic Stocks"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("SP500",tabName = "sp500"),
      menuItem("Ovintiv",tabName = "ovv"),
      menuItem("Planner",tabName = "plan"))),
  dashboardBody(
    tabItems(
      tabItem(tabName = "sp500",
              box(selectizeInput("sp",label = "Select Stock",choices = sp$Tickers,selected = "MMM", multiple = FALSE,options = NULL),
                  numericInput("days",label = "Days Back",min = 30,max = 1000,value = 90),
                  h4("Company Name"),
                  textOutput("company"),
                  br(),
                  h4("Sector"),
                  textOutput("sector"),
                  br(),
                  h4("Headquarters"),
                  textOutput("hq"),
                  br(),
                  h4("Yesterday's Closing Price"),
                  textOutput("current"),
                  br(),
                  h4("Last 30 Day AVG"),
                  textOutput("days30"),
                  br(),
                  h4("Last 30 Day Median"),
                  textOutput("days30_med"),
                  #radioButtons()
                  width = 3),
              box(h3("Company Stocks"),
                  plotlyOutput("line"),
                  br(),
                  h3("Sector Stocks"),
                  dygraphOutput("dygraph"),
                  width = 9)),
      tabItem(tabName = "ovv",
              box(dygraphOutput("ovv_dygraph"),
                  DTOutput("ovv_df"))),
      tabItem(tabName = "plan",
              box(title = "Set Your Current Situation",
                  numericInput("years","How many years in the future do you want to project?",value = 15),
                  numericRangeInput("expense","Monthly Expenses",value = c(0,100),separator = "to"),
                  numericRangeInput("income","Monthly Income",value = c(0,100),separator = "to"),
                  numericRangeInput("assets","What are your total liquid/total assets?",value = c(0,200000),separator = "to"),
                  numericInput("sims","How many simulations to run?",value = 500,min = 20,max=1000),
                  actionButton("sim_run",label = "Run the Simulator")),
              valueBoxOutput("life")))))